application: twachikku
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.(html|gif|jpg|png|js|css))$
  static_files: \1
  upload: .*\.(js|css|html|gif|png|jpg)$

- url: /(.*\.php)$
  script: \1

- url: .*
  script: main.php
