application: web592group99
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.+\.php)$
  script: \1

- url: /css
  static_dir: css

- url: /(.*\.(gif|png|jpg|html))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|html)$
  
- url: .*
  script: main.php
